services:
      oracle:
        image: gvenzl/oracle-free:latest
        environment:
          ORACLE_DATABASE: smartlab
          ORACLE_PASSWORD: oracle123
          APP_USER: smartlab
          APP_USER_PASSWORD: smartlab123
        ports:
          - "1521:1521"
        healthcheck:
          test: ["CMD", "healthcheck.sh"]
          interval: 30s
          timeout: 10s
          retries: 5
          start_period: 60s